- name: Exam
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:

    - name: Create exam
      docker_container:
        name: exam
        image: docker2706/examapp1
        pull: true
        state: started
        ports:
          - "80:80"